FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

CMD ["sh", "-c", "exec /opt/java/openjdk/bin/java -Dserver.address=0.0.0.0 -Dserver.port=${PORT:-80} -jar /app/app.jar"]