name: CI

on:
 push:
   branches: [main]
 pull_requests:
   branches: [main]

jobs:
   backend_test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@4

       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
       - name: Run backend tests
         working-directory: backend
         run: ./mvnw clean tests
   frontend-build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci 
      
      - name: Build frontend
        working-directory: frontend
        run: npm run build
